### ISSUE TITLE
access resources warning on installation 7.0.6

### ISSUE THREAD

**Issue by jorgelopezlago** [Southbank-Centre/OpenEvent#55]
During the instalation of v7.0.6 the following warnings are returned:
>Warning in features rebuild of oe_place. No module defines permission "access resource Place".
Warning in features rebuild of oe_event. No module defines permission "access resource Event".
Warning in features rebuild of oe_organization. No module defines permission "access resource Organization".
Warning in features rebuild of oe_person. No module defines permission "access resource Person".
![screenshot from 2015-07-09 15 36 13](https://cloud.githubusercontent.com/assets/889030/8598056/b6fb95b4-2650-11e5-9e59-2ff5ac966fc1.png)

**Comment by koutlas** [comment]
This is an issue that came up on development. Take a look at hook_node_type_insert in oe_schemaorg_rest module.

**Comment by samueljmurray** [comment]
This can be resolved now that each resource is named after the content type it serves, rather than the schema type that the content type is mapped to
