### ISSUE TITLE
JSON Api filtering not working as expected 

### ISSUE THREAD

**Issue by w32bit3** [Southbank-Centre/OpenEvent#58]
`/api/event.json?<propertyName>=<propertyValue>` not working - any query using any property name and value in this format returns page not found. Using Drupal 7.36

**Comment by tassoskoutlas** [comment]
Detailed documentation on the api is available on the path `/api/doc`. As it is documented there not all properties are available for filtering on the event type. The property `name` is supported as shown in the screenshot below:

![openevent-event-filtering](https://cloud.githubusercontent.com/assets/4750917/8761691/9329e8a4-2d56-11e5-9af8-f8bb6ff49148.png)

A non exhaustive list of properties not supported are:
- startDate
- endDate
- superEvent
- location
- subEvent
- performer

**Comment by w32bit3** [comment]
Dear Tassos,

Thank you for your help. I found the bug - it seems the problem only occurs
when the site is not using clean urls - the filters won't work when using
the /?q= url

It should be something like a mod rewrite issue. When I configured the
clean urls everything started working.

Thank you once again

Em sáb, 18 de jul de 2015 10:16, Tassos Koutlas <notifications@github.com>
escreveu:

**Comment by jorgelopezlago** [comment]
I have updated the requirements in the README to state the need for clean URLs enabled.
