### ISSUE TITLE
New Content Types show up on /api/doc but won't work in /api/contenttype.json

### ISSUE THREAD

**Issue by w32bit3** [Southbank-Centre/OpenEvent#66]
I've created a new content type called webpage, mapped it to shema.org "webpage" item,  and it shows on the documentation on /api/doc. When accessing /api/webpage.json all I get is an empty result set:

```javascript
{"self":"http:\/\/www.example.com/pt-br\/api\/webpage","first":"http:\/\/www.example.com\/pt-br\/api\/webpage?page=0","last":"http:\/\/www.mda.32bits.com.br\/pt-br\/api\/webpage?page=0","list":[{"isRelatedTo":[]},{"isRelatedTo":[]},{"isRelatedTo":[]},{"isRelatedTo":[]},{"isRelatedTo":[]},{"isRelatedTo":[]},{"isRelatedTo":[]},{"isRelatedTo":[]},{"isRelatedTo":[]},{"isRelatedTo":[]},{"isRelatedTo":[]},{"isRelatedTo":[]},{"isRelatedTo":[]}]}
```

**Comment by w32bit3** [comment]
Interestingly, if I query using the standard api syntax

    /node.json?type=webpage

Everything works fine.

**Comment by alexb-cogapp** [comment]
To show up on the schema.org API, the individual content type fields will need to be mapped to schema.org properties. You can do this from the field editing form - there should be a 'schema.org mapping' field at the bottom of the page which will auto-complete with valid properties.

**Comment by w32bit3** [comment]
yes, Alexb-cogapp, I've done it - as I've said, it actually shows the new content type (webpage) on the /api/doc documentation, but won't output the result of the query when accessing /api/webpage.json

**Comment by w32bit3** [comment]
Ok, thanks, I'll try that and report back.

**Comment by w32bit3** [comment]
It worked, thanks - but some fields like Language and Title, which are imported from the NODE structure can't be edited, which prevents me from inserting the correspondent schema.org properties... any ideas on how to fix this?

**Comment by alexb-cogapp** [comment]
As far as I recall, the [Schema.org](https://www.drupal.org/project/schemaorg) module should automatically map the Title field to the schema.org 'Name' property - is this not happening with your content type?

I don't believe the Schema.org module has support for mapping the language, so this would a matter of writing some custom code (*hook_restws_response_alter* might be a good place to start), or otherwise filing an issue with the [Schema.org](https://www.drupal.org/project/schemaorg) module.

**Comment by w32bit3** [comment]
Thank you, alex.
I can confirm the Title field mapping isn't happening. By the looks on the schema.org page, it's been 10 months from the last commit... not very good... I'll see what I can do. Thanks again.
